strict.perms: false

packetbeat.interfaces.device: any


packetbeat.flows:
  timeout: 30s
  period: 10s
  
packetbeat.protocols:
  - type: icmp
  - type: amqp
  - type: dns
    ports: [53]
  - type: http
    ports: [80, 81, 8080, 8000, 8888]
  - type: memcache
  - type: mysql
  - type: pgsql
  - type: redis
  - type: thrift
  - type: mongodb
  - type: cassandra
  - type: modbus
    ports: [502]
  - type: tls
    ports: [443]
  - type: sip
  - type: ftp
    ports: [21]
  - type: nfs
  - type: smb
  - type: dnp3
    ports: [20000]
  - type: mqtt
  - type: s7
    ports: [102]


# Lecture du fichier PCAP
packetbeat.pcap:
  file: "/pcap/4SICS-GeekLounge-151022.pcap"
  loop: true
  snaplen: 65535
  buffer_size_mb: 100

setup.template.enabled: false

# Sortie Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"
  username: ""
  password: ""

# Console output (pour debug si besoin)
output.console:
  enabled: false

setup.kibana:
  host: "http://kibana:5601"
